name: "[CI] Continuous Integration"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: "Generate SHA"
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      
      - name: Build docker image
        run: docker build -t maiconlourenco/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} . 

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push image
        run: |
         docker push maiconlourenco/nlw.service.passin:${{ steps.generate_sha.outputs.sha }}
         docker tag  maiconlourenco/nlw.service.passin:${{ steps.generate_sha.outputs.sha }} maiconlourenco/nlw.service.passin:latest
         docker push maiconlourenco/nlw.service.passin:latest